@host = https://creaconsult.krestdev.com/api
@token = 8b418372eac0fc41d5e1d81e187c0a5a67ead1280668efe350d2d17330af55208c36cfc17a7d35c8e09e92d4df84beb46afd9c390e87bc20c1da5a41d5b44cdb8565105f24550ca8fddac54613fe0ce6cba8ec4a1345507d51f37ea29325f82c199107571236157f7b7ee3bb291c869e407a96cd073db266726d896552efe1a5

### get contact
GET {{host}}/contacts
Authorization: Bearer {{token}}

### get Jobs
GET {{host}}/job?populate=*
Authorization: Bearer {{token}}

### get Job by id
GET {{host}}/job/1
Authorization: Bearer {{token}}

### get news
GET {{host}}/news?populate=*
Authorization: Bearer {{token}}

### get news
GET {{host}}/news/vg1dq6ixm2iptbcawfc3gb7j?populate=*
Authorization: Bearer {{token}}

###
GET https://betcreaconsultadmin.krestdev.com/api/jobs
Authorization: Bearer {{token}}